package kr.moare.android.utils

object StringResources {
    // button
    const val add = "추가"
     const val cancel = "취소"
     const val confirm = "확인"
     const val complete = "완료"
     const val search = "검색"
     const val member = "멤버"
     const val team = "팀"
     const val follower = "팔로워"
     const val following = "팔로잉"
     const val message = "메시지"
     const val update = "수정"
     const val delete = "삭제"
     const val report = "신고"
     const val block = "차단"
     const val unblock = "차단 해제"

    // navigation
     const val sportSelectNavigationTitle = "스포츠 종목 추가"
     const val postCreateNavigationTitle = "새 게시물"
     const val postUpdateNavigationTitle = "게시물 수정"
     const val teamProfileCreateNavigationTitle = "새 팀 프로필"
     const val profileUpdateNavigationTitle = "프로필 편집"
     const val settingsNavigationTitle = "설정"
//     const val accountInfoNavigationTitle = "계정"
//     const val infoNavigationTitle = "정보"
//     const val contactNavigationTitle = "문의"

    // login / join
     const val login = "로그인"
     const val join = "가입하기"
     const val forgotPassword = "비밀번호를 잊으셨나요?"
     const val emailTitle = "이메일 주소 입력"
     const val emailMessage = "입력한 이메일 주소로 인증코드가 전송됩니다."
     const val emailForNewPwdMessage = "비밀번호를 변경할 이메일을 입력해주세요.\n입력한 이메일 주소로 인증코드가 전송됩니다"
     const val authCodeTitle = "인증코드 입력"
     const val authCodeMessage = "주소로 전송된\n인증코드를 입력하세요."
     const val resendAuthCode = "인증코드 재전송"
     const val passwordTitle = "비밀번호 생성"
     const val usernameTitle = "사용자이름 생성"
     const val sportSelectTitle = "스포츠 선택"
     const val sportSelectMessage = "즐기는 스포츠를 1개이상 선택해주세요."
     const val sportSelectAlertMessage = "즐기시는 스포츠 추가 없이 회원가입 하시겠습니까?\n(추후에 프로필 편집을 통해 추가가 가능합니다)"
     const val joinFailAlertTitle = "회원가입 실패"
     const val joinFailAlertMessage = "회원가입에 실패하였습니다. 잠시후 다시 시도해 주세요."
     const val termsAgreeTitle = "약관 동의"
     const val termsAgreeMessage = "회원가입을 계속 진행하기 위해 약관을 동의해주세요"
     const val tosAgreeButton = "이용약관(필수)"
     const val privacyPolicyAgreeButton = "개인정보 처리방침(필수)"
     const val allTermsAgreeButton = "전체동의"
     const val termsDetailButton = "자세히 알아보기"
     const val loginInfoSaveTitle = "로그인 정보 저장"
     const val loginInfoSaveMessage = "님의 로그인 정보가 저장되므로 해당 기기에서는\n로그인 정보를 입력하지 않아도 됩니다."
     const val save = "저장"
     const val saveLater = "나중에하기"

    // location
     const val changeLocation = "지역 변경하기"
     const val deleteLocation = "지역 삭제"
     const val confirmToDeleteLocation = "를 삭제하시겠습니까?"
     const val confirmToSetLocation = "으로 지역을 설정하시겠습니까?"
     const val locationPermissionSettingTitle = "위치권한 설정"
     const val locationPermissionSettingMessage = "위치권한을 설정에서 허용해주세요"
     const val failedToGetAddress = "주소를 가져오는데 실패하였습니다."

    // sport
     const val failedToGetSportList = "스포츠 리스트를 가져오는데 실패하였습니다."

    // profile
     const val addProfilePhoto = "사진 추가"
     const val teamProfileCreateButton = "팀 프로필 생성"
//     const val profileUpdateButton = "프로필 편집"
     const val teamProfileLimitAlertTitle = "팀 프로필 개수 제한"
     const val teamProfileLimitAlertMessage = "팀 프로필은 한 계정당 최대 10개까지만 생성 가능합니다."
     const val followButton = "팔로우"
     const val unfollowButton = "팔로우 취소"
     const val createProfileButton = "생성"
     const val reportUserAlertTitle = "사용자 신고하기"
     const val reportUserAlertMessage = "이 사용자를 \"부적절한 컨텐츠를 포함\"한 사유로 신고하시겠습니까?"
     const val blockUserAlertTitle = "사용자 차단하기"
     const val blockUserAlertMessage = "이 사용자를 차단하시겠습니까?"
     const val blockUserSuccessMessgae = "(이)가 차단되었습니다"

    // post
     const val setCurrentLocationMessage = "운동을 즐기시는\n지역을 설정해주세요."
     const val setCurrentLocation = "지역 설정하기"
     const val noPostInCurrentLocation = "주변 지역에 게시물이 없습니다."
     const val noMorePost = "게시물이 더이상 없습니다."
     const val createPostAlertTitle = "게시물 작성"
     const val createdPostAlertMessage = "지역을 설정해야 게시물 작성을 할 수 있습니다."
     const val upload = "게시"
     const val videoLengthLimitAlertTitle = "영상 길이 제한"
     const val videoLenthLimitAlertMessage = "영상 길이는 30초 이하로 제한됩니다"
     const val mediaCountLimitAlertTitle = "게시물 사진/영상 개수 제한"
     const val mediaCountLimitAlertMessage = "게시물의 사진/영상 개수는 최대 10개입니다"
     const val deletedPostMessage = "삭제된 게시물입니다"
     const val reportPostAlertTitle = "게시물 신고하기"
     const val reportPostAlertMessage = "이 게시물을 부적절한 게시물로 신고하시겠습니까?"

    // settings
     const val deleteTeamProfileButton = "팀프로필 삭제"
     const val deleteAccountButton = "계정삭제"
     const val tos = "이용약관"
     const val privacyPolicy = "개인정보 처리방침"
     const val locationTos = "위치기반서비스 이용약관"
     const val account = "계정"
     const val info = "정보"
     const val questions = "문의"
//     const val contactEmailMessage = "문의사항은 ymb3264@naver.com으로 문의주시기 바랍니다."
     const val logoutButton = "로그아웃"

    // stream chat
     const val deleteChannelAlertTitle = "채팅방 영구적으로 삭제"
     const val deleteChannelAlertMessage = "채팅방을 영구적으로 삭제하시면 상대방도 이 채팅방을 더 이상 볼 수 없게됩니다."
     const val leaveTeamChannelAlertTitle = "채팅방 나가기"
     const val leaveTeamChannelAlertMessage = "팀을 언팔로우 하시면 채팅방에서 자동으로 나가집니다."
     const val noChannelMessage = "채팅방이 없습니다"

    // error
     const val emailValidationError = "이메일 형식을 확인해주세요"
     const val loginError = "이메일 또는 비밀번호를 확인해주세요"
     const val wrongAuthCodeError = "인증번호가 틀립니다."
     const val failedToSendAuthCode = "인증번호 전송에 실패하였습니다.\n다시 시도해주세요."
     const val passwordValidationError = "비밀번호가 유효하지 않습니다."
     const val wrongPasswordForCheck = "비밀번호가 다릅니다."
     const val usernameValidationError = "사용자 이름에는 영어 대/소문자, 숫자,\n밑줄(_) 및 마침표(.)만 사용할 수 있습니다."
     const val existingUsernameError = "이미 사용중인 사용자이름입니다."
     const val failedToGetProfileInfo = "프로필정보를 가져오는데 실패하였습니다."
     const val failedToGetUserPost = "게시물을 가져오는데 실패하였습니다."

    // placeholder
     const val findLocationPlaceholder = "동명(읍, 면)으로 검색해주세요 (ex. 서초동)"
     const val hostPlaceholder = "(생성자)"
     const val emailPlaceholder = "이메일"
     const val passwordPlaceholder = "비밀번호"
     const val passwordForCheckPlaceholder = "비밀번호 확인"
     const val authCodePlaceholder = "인증코드"
     const val postCreateContentPlaceholder = "내용입력(첫째줄은 메인에 표시됩니다.)"
     const val addMediaPlaceholder = "사진 및 영상 추가"
     const val postCreatePreviewPlaceholder = "미리보기\n(터치 시 상세화면으로 이동)"
     const val sportPlaceholder = "운동종목"
     const val locationPlaceholder = "지역"
     const val teamProfileCreateContentPlaceholder = "팀 정보(소개)"
     const val teamUsernamePlaceholder = "팀 사용자 명"
     const val teamNamePlaceholder = "팀 명"
     const val updateProfileContentPlaceholder = "소개"
     const val namePlaceholder = "이름"

    // info
     const val postCreateMediaDeleteInfo = "스포츠 관련 사진/영상이 아닐경우 게시물이 삭제될 수 있습니다."
     const val postCreateSportInfo = "· 필수 입력칸입니다.\n· 해당 게시물을 나타내는 운동종목을 추가해보세요.\n· 여러종목이 선택가능하며, 없는 종목은 적어서 추가할 수 있습니다."
     const val postCreateLocationInfo = "· 필수 입력칸입니다.\n· 운동을 즐긴 지역을 추가해보세요.\n· 추가된 지역 주변으로 게시물이 노출됩니다."
     const val postCreateMediaInfo = "· 영상 길이는 30초 이하로 제한됩니다.\n· 게시물의 사진/영상 개수는 최대 10개입니다."
     const val postUpdateMediaInfo = "게시물의 사진/영상은 수정할 수 없습니다."
     const val teamNameInfo = "· 필수 입력값입니다.\n· 팀명은 알파벳, 숫자 이외에도 자유롭게 작성가능합니다.\n· 팀 프로필 생성시 자동 생성되는 팀 채팅방 이름이 작성된 팀명으로 설정됩니다."
     const val sportInfo = "· 프로필에 즐기는 운동을 추가해보세요.\n· 여러종목이 선택가능하며, 없는 종목은 적어서 추가할 수 있습니다."
     const val locationInfo = "· 운동을 주로 즐기는 지역을 추가해보세요."

    // common alert
     const val deleteFormTitle = "작성내용 삭제"
     const val deleteFormMessage = "작성중인 내용이 삭제됩니다"
     const val requiredFormAlertMessage = "필수 입력칸을 작성 완료해 주세요"
     const val reportSuccessMessgae = "신고가 정상적으로 접수되었습니다"

    // etc
     const val today = "오늘"
     const val seeMore = "더보기"

    // api
     const val tosUrl = "https://moare.kr/info/tos"
     const val privacyPolicyUrl = "https://moare.kr/info/privacy_policy"
     const val locationTosUrl = "https://moare.kr/info/location_tos"
}